### ISSUE TITLE
A list of ideas and problems

### ISSUE THREAD

**Issue by Snorrrlax** [PixelOrange/MARS#20]
After trying to explain to a few people things that need to be done, and realising that the information was quite messy (having to send a link to an issue on the old repo, the new repo, a closed issue that actually doesn't work etc.), I thought it would make sense to compile it here. To clarify, this list is general ideas. As I can't code, I can't comment on any problems with the script. Maybe someone else will add that as a comment below. I will be largely linking to issues, open and closed, throughout this.

* The delta leaderboard(s)

A while ago we had a monthly leaderboard in the sidebar titled "top ten viewchangers", and it worked fine. Somewhere along the line something went wrong, and it was taken down until it was fixed, but it is yet to be fixed.

On top of this, we have a wiki page for more delta leaderboards of different time scales (http://www.reddit.com/r/changemyview/wiki/leaderboards), which is currently defunct. We'd like this to work as well. 

A few more issues surrounding this subject:

Fair listing of leaderboard: [First issue](https://github.com/alexames/DeltaBot/issues/3), which was referenced in a [second issue](https://github.com/alexames/DeltaBot/issues/59). Basically, we need to make sure the ordering of users in the leaderboard makes sense and is fair. So if two people have the same score, the person who is above the other in the list is the one who got the score first, instead of ordering it alphabetically, for example.

Highlight the flair of users on the monthly leaderboard: [First issue](https://github.com/alexames/DeltaBot/issues/18), referenced in a [second issue](https://github.com/alexames/DeltaBot/issues/64) when it became problematic. 

I would also like to highlight [this issue](https://github.com/alexames/DeltaBot/issues/62) which concerns the layout of the leaderboard.

* Auto-PM a user when they receive their first delta.

Explained in [this closed issue](https://github.com/alexames/DeltaBot/issues/2), but isn't up and running. I think it might be related to [this issue](https://github.com/alexames/DeltaBot/issues/60) about DeltaBot struggling to recognise first deltas.

* "Delta queue" mod tool.

Explained in [this issue](https://github.com/alexames/DeltaBot/issues/4). I'm not completely sure what has stopped it from being implemented so far, but I think it might be related to [this issue](https://github.com/PixelOrange/MARS/issues/8) about a delete command. I'd love to see this become a reality.

* Delta history wiki pages.

I think there are problems with the whole wiki system, but PixelOrange would be best to ask about this, and I think he is working on fixing it. One of the issues I've noticed is incorrect delta totals on wiki pages. [Here is the issue](https://github.com/alexames/DeltaBot/issues/61), and [here's an example](http://www.reddit.com/r/changemyview/wiki/user/sennalvera) of the problem.

* An interactive wiki page correction system.

This is a new idea I've just had based on the fact that quite often our problems are ones that can be fixed, but are hard to retroactively apply. For example, and my memory is a bit foggy here, a reddit bot can only scan through a limited number of comments. If DeltaBot went dead long enough for more comments than this limit to be created, some of which possibly including deltas, then DeltaBot wouldn't be able to add them unless manually notified. 

Basically, I think we should set up a system where if a user notices a problem with the information on their wiki page, user flair etc, then they should be able to follow a couple of steps to get it fixed that doesn't actually require the moderators' involvement.

For example, a link could be put at the bottom of each wiki page saying: 

"Is this wiki page displaying incorrect information? Has DeltaBot missed one of your deltas? Please follow these instructions (link to another wiki page) to get it fixed."

The linked wiki page would then have a list of some potential problems, such as missed delta, incorrectly given delta, incorrect delta count on delta history page etc. which link to pre-made messages to DeltaBot, which it receives and acts upon. 

I hope this idea has made sense. Of course, with a perfect DeltaBot this wouldn't be necessary if it wasn't for the difficulty of dealing with past information.

* I think this is everything major at the moment. I'll score them off as they are dealt with, or add more that I might have forgotten. Thanks!

**Comment by PixelOrange** [comment]
Most of the bugs with the old code will be non-issues in this version. 

* PMing will be triggered when the user is given their first flair. 

* The new wiki pages are stored as tables instead of tacky lists and are sorted by date awarded.

* The leaderboard ordering will be normalized in a similar way to what the user delta history already has been.

* The delta queue may become overwhelming if people forget to check it but that should also be a fairly easy implementation with the new code.

* The delta correction system will be easy enough to do as well. I've already coded a "correction system" for users to use themselves. I'd just have to write a document on how to use it. :)

Currently the project is hung as a wiki incompatibility. I need to convert all of the user/wiki pages or migrate them to a history system and then I can proceed further with the project. Since I've spoken to you about that already, I should be able to complete this step in the next week or so.

**Comment by Snorrrlax** [comment]
Ah, I didn't realise that a lot of these things would be dealt with over here. I was talking to these other people about all this when it would clearly just have confused things. I'm glad you're back on it!

Sounds good to me. As for the delta queue being overwhelming, having the first in first out system should help with this. Even if a delta hasn't been approved for the longest time, it'll still be at the top of the list, making it hard to miss any. Is this how the mod queue does it?

**Comment by PixelOrange** [comment]
I believe the mod queue does FIFO but I'm not sure. I think the current system I've implemented sorts by username so I will disable that to allow for FIFO. Actually, I will probably do both. One that's a user listing of all people awarded deltas and one that's the mod queue for allowing what you want here.

**Comment by Snorrrlax** [comment]
Great :) speaking of FIFO, while I definitely think this is the correct method for the delta queue, I think delta history should be the opposite- ie the user's wiki page displays their most recent deltas on the top. What do you think?

**Comment by PixelOrange** [comment]
Delta History is now ordered: Date, Submission, Delta Comment, Awarded By. In addition, it now sorts in reverse (newer dates on top). I'm going to open a new issue for the Delta Queue because it'll never get done if it's in here.
