### ISSUE TITLE
Dealing with deltas in edits

### ISSUE THREAD

**Issue by Snorrrlax** [PixelOrange/MARS#29]
I've just realised that mods have a mod tool that allows us to see recently edited comments and posts. [This was announced six months ago](http://www.reddit.com/r/modnews/comments/2dgmd4/moderators_edited_page_now_available_at/), but I must've missed it. 

I'm not sure what the current situation is, but I know in the past one of the problems was dealing with deltas that were added in edits, because a user didn't know about them or how to use them. It's always been a bit clunky, having to trigger deltabot to rescan etc. 

However, as DeltaBot is a mod and has access to this "edited" mod tool, does that make it possible to just add these edited comments into the queue? So while DeltaBot is scanning every new comment, it is also scanning the edited queue for added deltas? 

This way, a delta can be added at any time, and DeltaBot will be aware of it. That would be great.

**Comment by PixelOrange** [comment]
Not currently. It's a feature we can certainly add. I saw it when it was
announced but I haven't had the chance to look into how it works yet.

**Comment by Snorrrlax** [comment]
Okay cool, I'm glad to hear it's possible!

**Comment by PixelOrange** [comment]
I dislike how they handle edited comments. I don't know if it'll work using the edit queue but I'll come up with something if I can't use that.

**Comment by PixelOrange** [comment]
Edited comments are no longer ignored in history.
