### ISSUE TITLE
Some formatting issues in the delta queue

### ISSUE THREAD

**Issue by Snorrrlax** [PixelOrange/MARS#30]
http://www.reddit.com/r/changemyview/wiki/deltabot/queue

Links are messing up a bit

**Comment by Snorrrlax** [comment]
I compared the queue to the track page and found the problem: If a delta comment has paragraph breaks in it, the link fails at the first paragraph break. The links that have worked are comments that contain only one paragraph.

**Comment by PixelOrange** [comment]
That was my conclusion as well. I will strip line breaks from future versions.

**Comment by PixelOrange** [comment]
Fixed
