### ISSUE TITLE
Usernames in DeltaBot's comments are all lower case.

### ISSUE THREAD

**Issue by Snorrrlax** [PixelOrange/MARS#32]
See here: https://www.reddit.com/r/changemyview/comments/2vgdvl/cmv_planet_should_not_be_part_of_the_triple/coi5mp6?context=3

Compared to before: https://www.reddit.com/r/changemyview/comments/2v7rbo/cmv_i_dont_think_that_we_know_enough_about_our/cog156l?context=3

**Comment by PixelOrange** [comment]
When it checks for matches it puts them all lowercase to avoid casing issues, this is just a carry over from that. Should be easy to fix.

**Comment by PixelOrange** [comment]
Confirmations will now use the appropriate casing.
