### ISSUE TITLE
Improving the remove process.

### ISSUE THREAD

**Issue by Snorrrlax** [PixelOrange/MARS#38]
http://www.reddit.com/r/changemyview/comments/2w8w4q/cmv_there_is_no_point_to_use_anesthesia_in/coomm4t

This is our first use of the remove tool from the delta queue I think. Firstly, DeltaBot's comment isn't distinguished, but secondly I think DeltaBot's response needs to be edited to include the reason why this delta in particular was rejected. 

Although, as mentioned in modmail, it would be good to specify the reason for removal in the PM to DeltaBot (subject line was a good suggestion!).

Also, I think IAmAN00bie's suggestion [here](http://www.reddit.com/message/messages/30m38u) was a good one.

**Comment by PixelOrange** [comment]
Added bug tag for the distinguish portion.

Try not to link to suggestions that are private or people who aren't a part of CMV won't be able to view them if they're ever looking at the past issues.

The distinguish is fixed. The DeltaBot custom responses have been implemented. I'll update the header to include information on how to use the delta queue.
