### ISSUE TITLE
Table formatting issue in delta queue.

### ISSUE THREAD

**Issue by Snorrrlax** [PixelOrange/MARS#39]
There's currently a formatting issue with the table, just in case you weren't aware: http://www.reddit.com/r/changemyview/wiki/deltabot/queue.

By the way, is it worth making an issue for something like this or should I just PM you?

**Comment by PixelOrange** [comment]
Always make issues in case I can't get to it right away.

**Comment by PixelOrange** [comment]
Forgot to include a line break which is what caused this. I also caught two other bugs while fixing this that hadn't surfaced yet, thankfully.
