### ISSUE TITLE
DeltaBot's confirmation comment.

### ISSUE THREAD

**Issue by Snorrrlax** [PixelOrange/MARS#40]
I wanted to discuss DeltaBot's confirmation comment.

It originally said this:

> Confirmed: 1 delta awarded to /u/Snorrrlax. ^[[History](/r/changemyview/wiki/user/snorrrlax)]

> ^[[Wiki](http://www.reddit.com/r/changemyview/wiki/deltabot)][[Code](https://github.com/alexames/DeltaBot)][[Subreddit](http://www.reddit.com/r/DeltaBot/)]

With MARS up and running, this was scrapped, and this concern was raised:

> I have always disliked that it just says "History". History of what? Snorrrlax's History (or Snorrrlax's Delta History) seems more descriptive to me and it's not like we're hurting for space.
We can shrink the size of the text if necessary but I'm pretty sure those user history pages are severely underutilized and I think if we included more information at the sacrifice of brevity we would get more hits.

Which I actually agree with, but it now says this: 

> Confirmed: 1 delta awarded to /u/Snorrrlax.

> ^^[ [^^Awardee's ^^History](/r/changemyview/wiki/user/snorrrlax) ^^]

which I think could be improved further, to something like this:

> Confirmed: 1 delta awarded to /u/Snorrrlax. 

> *^See ^also: ^Snorrrlax's ^delta ^[history](http://www.reddit.com) ^and ^the ^delta ^system ^[wiki](http://www.reddit.com).*

For some reason the superscript markdown doesn't work here, but it would look like this (with the second line smaller):

> Confirmed: 1 delta awarded to /u/Snorrrlax. 

> *See also: Snorrrlax's delta [history](http://www.reddit.com) and the delta system [wiki](http://www.reddit.com).*

I think only one ^ is necessary, ^^ makes it look a bit too small.

**Comment by PixelOrange** [comment]
Going from ^^ to ^ is purely preference and I have none so consider that done.

How about [Snorrrlax's Delta History](http://linkto) | [Delta System Wiki](http://linkto)

**Comment by Snorrrlax** [comment]
I like that. The only problem is having multiple words in a link breaks when using superscript.

**Comment by Snorrrlax** [comment]
You know what, I really do like that, perhaps it doesn't need the superscript?

**Comment by PixelOrange** [comment]
That was decided before me. It's up to you, but no, currently there are two words in the link and it works fine.

**Comment by Snorrrlax** [comment]
Ah yes, I was doing it wrong! I think it should be this then:

Confirmed: 1 delta awarded to /u/Snorrrlax.

[^Snorrrlax's ^Delta ^History](http://www.reddit.com) ^| [^Delta ^System ^Wiki](http://www.reddit.com)

**Comment by PixelOrange** [comment]
You know, every time you do this you make me add more variables to my script.

h8u!

**Comment by Snorrrlax** [comment]
<3 u

**Comment by Snorrrlax** [comment]
Speaking of DeltaBot comments, I think this:

> This delta is currently disallowed as your comment contains either no or little text ([comment rule 4](http://www.reddit.com/r/changemyview/wiki/rules#wiki_rule_4)). Please include an explanation for how /u/PixelOrange changed your view. Please respond to this comment once you have made the necessary changes.

Should be changed to this:

> This delta is currently disallowed as your comment doesn't include enough (or any) text ([comment rule 4](http://www.reddit.com/r/changemyview/wiki/rules#wiki_rule_4)). Please include an explanation for how /u/PixelOrange changed your view. If you do this, responding to this comment will make me recheck yours.

Which explains what's happening a bit better I think.

**Comment by PixelOrange** [comment]
Updated. Just PM me if it needs reopened, don't bother making a new onem
