### ISSUE TITLE
Formatting in delta queue

### ISSUE THREAD

**Issue by Snorrrlax** [PixelOrange/MARS#48]
When deltabot adds a delta to the queue, the formatting looks like [this](http://imgur.com/fk5iclU). When it removes an entry from the queue, it looks like [this](http://imgur.com/MRqwktX).

**Comment by PixelOrange** [comment]
I assume you're referring to the approve/reject descriptions and the loweffort header? Anything else?

**Comment by Snorrrlax** [comment]
Yeah. I don't think there's anything else formatting wise.

**Comment by PixelOrange** [comment]
Fixed.
